person:
  userName: zhangsan
#双引号不会转义 单引号会
  boss: true
  birth: 2019/12/4
  age: 12
  #interests: [篮球，足球]
  interests:
    - 篮球
    - 足球
  animal: [猫，狗]
  #score: {key: value}
  score:
    english: 80
    math: 90
  salarys:
    - 9999.98
    - 9999.99
  pet:
    name: 1
    weight: 9.99
  allPets:
    sick:
      - {name: 1,weight: 9.99}
      - name: 2
        weight: 8.88
      - name: 3
        weight: 7.77
    health:
      - {name: 4,weight: 6.66}
      - name: 5
        weight: 5.55